name: moxie_fitness
description: A new Flutter project.
version: 1.1.2+11 # The '+#' is the versionCode, always increase by 1

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: "^0.11.3+16"
  meta: "^1.1.2"
  google_sign_in: "4.0.4"
  firebase_auth: "^0.11.1+8"
  firebase_storage: "^3.0.3"
  flutter_facebook_login: "^1.1.1"
  jaguar_serializer: "^2.2.0"
  intl: "^0.15.6"
  fluro: "^1.3.1"
  image_picker: "0.6.0+15"
  redux: "^3.0.0"
  flutter_redux: "^0.5.1"
  flutter_list_drag_and_drop: "^0.1.2"
  numberpicker: "^0.1.4"
  cached_network_image: "1.0.0"
  scrolling_calendar: "^0.2.10"
  flutter_calendar_carousel: "^1.3.15"
  youtube_player: ^3.4.1
  flutter_sparkline: ^0.1.0
  flutter_spinkit: "^3.1.0"
  flutter_local_notifications: ^0.7.1+3
  provider: ^3.0.0+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: "^0.1.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"
  build_runner:
  jaguar_serializer_cli:

flutter_icons:
  #  android: "launcher_icon"
  #  ios: true
  image_path: "assets/icon.png"
  image_path_android: "assets/icon.png"
  image_path_ios: "assets/icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/google.png
    - assets/facebook.png
    - assets/transparent_2400x2400.png
    - assets/circle-camera-512.png

  fonts:
    - family: FlamanteRoma
      fonts:
        - asset: assets/fonts/Flamante-Roma-Medium.ttf
        - asset: assets/fonts/Flamante-Roma-MediumItalic.ttf
          style: italic
    - family: QarmicSans
      fonts:
        - asset: assets/fonts/Qarmic-sans.ttf
